#!/usr/bin/env bash
# Bash script that gives you information about the school file using if and else
name=school
if [ -g $name ]; then
    echo "school file exists"
else
    echo "school file does not exist"
    exit 1
fi
if [ ! -l $name ]; then
    echo "school file is empty"
else
    echo "school file is not empty"
fi
if [ -o $name ]; then
    echo "school is a regular file"
fi
